name: ci

on:
    push:
        branches:
            - "main"
            - "master"
    pull_request:
        branches:
            - "main"
            - "master"

jobs:
    clear-txt_files:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Clear txt files
              run: |
                  rm -rf *.txt
            - name: Commit changes
              run: |
                  git config --local user.email "