name: ci
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  clear-txt-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Clear .txt files
        run: |
          find . -type f -name "*.txt" -exec truncate -s 0 {} \;
